### ISSUE TITLE
Broken migration to Modoboa 1.15.0 from 1.14.0

### ISSUE THREAD

**Issue by fluboi** [modoboa/modoboa-installer#332]
# Impacted versions

* Distribution: Debian 10.4
* Codename: Buster
* Arch: 64 Bits
* Database: PostgreSQL

# Steps to reproduce
 - Create new venv with python3
 - pip install modoboa (1.15.0)
 - pip install extensions and psycopg2
 - try to run manage.py migrate
 
```
(env-py3) modoboa@mail:~/instance$ python --version
Python 3.7.3

(env-py3) modoboa@mail:~/instance$ python manage.py migrate                                                                                                                                                       
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line                                                                              
    utility.execute()
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute                                                                                                
    django.setup()
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models                                                                                                       
    self.models_module = import_module(models_module_name)
  File "/srv/modoboa/env-py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/modoboa_pfxadmin_migrate/models.py", line 89, in <module>                                                                                                
    class DomainAdmins(models.Model):
  File "/srv/modoboa/env-py3/lib/python3.7/site-packages/modoboa_pfxadmin_migrate/models.py", line 90, in DomainAdmins                                                                                            
    username = models.ForeignKey(Admin, db_column='username')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

# Expected behavior
Currently using modoba 1.14.0, when upgrading to 1.15.0 after creating a new python3 venv, it fails. 
Documentation says "If you upgrade an existing python 2 installation, you will need to create a new Python 3 virtual environment. You can remove the existing virtual environment and replace it by the new one so you won’t have to modify your configuration files."

**Comment by fluboi** [comment]
Not open under the good projet... sorry
